### ISSUE TITLE
[EPIC] ☂️ Recover clusterwide configuration consistency

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1142]
Consider following scenarios:

## Case 1 (#1046)

- A user uploads a config.
- Prepare stage succeeds
- But the commit stage fails on a single instance
- User sees an issue: Configuration checksum mismatch on localhost:3303 (srv-3)
- Uploading the same config says "OK", but the issue remains.

## Case 2 (#1087)

- A user uploads a config.
- Prepare stage fails on a single instance because it goes offline and fails to reply
- There are no issues
- But further uploads fail with the message "Two-phase commit is locked"
- A user has to remove `config.prepare` manually

## Case 3

- A user uploads a config.
- Prepare stage succeeds.
- Commit stage fails because one of the instances enters OperationError state.
- Uploading the same config says "OK", but OperationError remains.

## Case 4

- A user uploads a config.
- Everything is OK.
- One instance is stopped.
- Uploading the same config says "OK" despite the quorum is lost.

## Solution plan

- [x] Implement issue to indicate that config is locked (#1146)
- [x] Implement API to force-apply config on specified instances (#1144)
- [x] Implement suggestion API to force-apply config (either locked or mismatching or OperationError) (#1187)
- [x] Implement suggestion API to disable unreachable instances (#1068)
- [x] Show an issue when ConfiguringRoles hangs (#1172)
- [x] Don't skip two-phase commit prematurely (#1046)
- [x] Design force-apply suggestion (https://github.com/tarantool/ux_ui/issues/73)
- [x] Design disable suggestion (https://github.com/tarantool/ux_ui/issues/37)
- [x] Implement force-apply suggestion in WebUI (#1238)
- [x] Implement disable suggestion in WebUI (#1237)
- [x] Test disable servers suggestions (#1277)
- [x] Test force apply config suggestions (#1289)
- [x] Properly display disabled instances in WebUI (https://github.com/tarantool/ux_ui/issues/66, #982)
- [x] Fix hardcoded timeout for prepare_2pc (#1145)

## To think about

- Prohibit joining an instance to a replicaset with all replicas disabled (#32)
- Config validation flaw: instance stealing (#892)
- #1204
