### ISSUE TITLE
☂️[EPIC] FaaS framework for private installations

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1210]
Как разработчик решений на Tarantool, я хочу иметь возможность

1. Доставлять код бизнес-логики в развернутый кластер Tarantool без выполнения полного цикла разработки и развертывания кластерной роли;
2. В 1 действие получить кластерное приложение, готовое к доставке кода в него, чтобы мне не приходилось руками конфигурировать роли на узлах.

Мне это нужно чтобы как можно быстрее получить работающее решение без написания бойлерплейта и лишних временных затрат, а также чтобы доставлять код в кластер прямо из своей среды разработки.

## **Критерии приемки**

1. При установке или запуске Tarantool в облаке пользвоателю доступна возможность выбрать продуктовую конфигурацию **easy_functions**
2. Если пользователь выбрал эту опцию, то при создании кластерного приложения автоматически выполняется следующее:
    1. Добавляется роль *extensions,*
    2. Добавляются соответствующие зависимости и устанавливаются необходимые роки;

    *Примечание: для роли extensions устанавливаются следующие rocks:*

    - *extensions*
    - *migrations*
    - *crud*
3. Роль extensions по-умолчанию включается на всех узлах всех репликасетов кластера, в котором она установлена;  
4. Пользователь не видит эту роль в админке и не может отключить эту роль через стандартные средства управления конфигурацией кластера (WebUI, CLI, API)
5. Пользователь имеет возможность добавлять свой код в модуль *extensions* через встроенный редактор в WebUI Tarantool 
6. Доставка пользовательского кода в роль *extensions* производится путем размещения файлов с кодом в модуле с именем *extensions;*
7. Пользователь имеет возможность добавлять свой код в модуль *extensions* через API (тот же самый, через который работает UI). Загрузка кода происходит путем отправки файла с кодом или tar-архива с несколькими файлами.
8. Сразу после того, как пользователь добавил код в роль, автоматически производится его проверка на предмет корректной загрузки;
9. В случае неудачной проверки добавленного кода по любой причине его применение не производится и уже существующий код в роли extensions остается неизменным;
10. В случае успешной проверки загруженного кода он автоматически применяется к роли и распространяется по всем узлам кластера.

### Установка on-premise

1. Пользователь устанавливает Cartridge стандартным способом
2. При создании приложения пользователь указывает ключ “--extensions”

### Try-cartridge

Try уже содержит установленную роль extensions. Пользователь может открыть try-cartridge и начать работать ничего не устанавливая.

## To do
- [x] Анализ и RFC
- [x] Прототип cartridge-extensions
- [x] Поддержка HTTP в cartridge-extensions
- [ ] Move try-cartridge to a personal repo (easy-functions?) - 2
- [ ] Discuss and define distribution ways.
- [ ] Add migrations support - 8
- [ ] Test crud integration - ?
- [x] Modern try-cartridge is incompatible with 1.10, is it ok? - yes
- [ ] Provide a migration template on the Code page (https://github.com/tarantool/migrations/issues/32) - 2
- [x] Provide cartridge-extensions template on the Code page (https://github.com/tarantool/cartridge-extensions/issues/11) - 2
- [ ] Make cartridge-extensions role permanent - 2
- [ ] (?) Change code in "How to connect" section (#637) - 8
- [ ] https://github.com/tarantool/cartridge/issues/1085 - 16 
- [ ] https://github.com/tarantool/cartridge/issues/1219 - 16
- [ ] (?) Upload/download archived config (#523) - ? 
- [ ] Документация по cartridge-extension и FaaS в целом - ? 

= 54 sp

**Comment by srgkvlv** [comment]
Сделали on-premise MVP, дальше нужно собирать фидбэк и тащить в облако.
