### ISSUE TITLE
☂️ Enormous clusters over 1k

### ISSUE THREAD

**Issue by rosik** [tarantool/cartridge#1212]
Ansible team:
- [x] Deploy cluster with 1k nodes via `ansible-cartridge` for proving of that feature (https://github.com/tarantool/ansible-cartridge/issues/291)
https://github.com/tarantool/ansible-cartridge/issues/293
    - [x] The app doesn't have to be dumb. Blank TDG's deployment seems OK  
    - [x] For that deployment needs real scenarios with topology  

After testing we've stuck with the next problems:
- [x] Stateboard's file descriptors limit is reached at 1k cluster (https://github.com/tarantool/cartridge-cli/issues/549)
- [x] Stateboard's net_msg_max value by default is reached at 1k cluster  (tarantool/cartridge-cli#551)
- [x] https://github.com/tarantool/huge-cluster-deployer/issues/4
- [x] Ansible-role optimisation to deploy 1K+ clusters (Improved cluster deployment performance by using Ansible-role tarantool/roadmap-internal#52)

**Comment by alexeykoryakin** [comment]
Moved "TDG's readahead option isn't dynamic and too big for 1k cluster" and "Check 1K Cluster work during load testing" to the another epic tarantool/roadmap-internal#26 "[Epic] Productization of enormous clusters"
