### ISSUE TITLE
Move cluster to open-source (epic)

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#135]
In GitLab by @sharonovd on Jul 16, 2019, 14:43

Umbrella ticket for related activities

- [ ] Move membership to github
- [ ] Publish membership rockspec in tarantool/rocks
- [ ] Move frontend-core to github
- [ ] Publish frontend-core rockspec in tarantool/rocks
- [ ] Publish cluster on github
- [x] Release cluster 0.10
- [ ] tarantoolapp: resolve related issues
- [ ] Move tarantoolapp to github
- [ ] Implement cluster version reporting (feedback daemon)
- [ ] Post on habr
- [ ] Write getting started guide
- [x] tarantoolctl: Allow to use NOTIFY_SOCKET without `box.cfg{}` [gh-4305](https://github.com/tarantool/tarantool/issues/4305)
- [ ] tarantoolctl: Relolve forking tarantoolctl? [gh-4381](https://github.com/tarantool/tarantool/pull/4381)
- [ ] tarantoolctl: Configure logger without calling `box.cfg{}`? [gh-689](https://github.com/tarantool/tarantool/issues/689)

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 13:47

marked this issue as related to tarantoolapp#3

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 13:47

marked this issue as related to tarantoolapp#1

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 16:59

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 17:00

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 17:00

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 17:01

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 17:37

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 1, 2019, 17:39

changed the description

**Comment by sharonovd** [comment]
In GitLab by @rosik on Aug 2, 2019, 12:10

marked this issue as related to #29

**Comment by sharonovd** [comment]
In GitLab by @sharonovd on Aug 9, 2019, 11:01

marked the task **Release cluster 0.10** as completed

**Comment by sharonovd** [comment]
And it is done
