### ISSUE TITLE
☂️ Compact Cluster page

### ISSUE THREAD

**Issue by rgbabaev** [tarantool/cartridge#1388]
## Parts:
- [x] Optimize Cluster page queries #1389
- [x] Revise queries made by the WebUI #1182
- [x] Update Cluster list UI #1390
- [x] Use effector instead of redux #797
- [x] Update Cluster page filter
