### ISSUE TITLE
External storage for Stateful failover

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/cartridge#805]
For some of our customers, we need this feature for durable storing topology configuration.

etcd/consul as the primary candidates, of course.

Problem decomposition:

- [x] Research etcd functionality and API
- [x] (#826) Implement etcd-client, cover it with unit tests
- [x] (#827) Implement etcd support in clusterwide config
- [x] (#828) Implement etcd_params in GraphQL API
- [x] (#829) Redesign failover dialog in WebUI (stateboard/etcd switcher)
  and implement it in frontend.

**Comment by rosik** [comment]
Problem decomposition:

- [ ] Research etcd functionality and API
- [ ] Implement etcd-client, cover it with unit tests
- [ ] Implement etcd support in clusterwide config
- [ ] Implement etcd_params in GraphQL API
- [ ] Redesign failover dialog in WebUI (stateboard/etcd switcher)
- [ ] Implement frontend for redesigned failover dialog
