### ISSUE TITLE
[EPIC] ☂️ Pluggable config storage for Cartridge

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#91]
In GitLab by @sharonovd on Apr 29, 2019, 11:22

Currently cluster stores instance config on file system.
It would make things easier for some deployments, if it would be possible to store it in centralized way (e.g. etcd, consul, zookeeper).

- [x] https://github.com/tarantool/roadmap-internal/issues/7
- [x] Prototype for topology module
- [x] Prototype for config module
- [ ] https://github.com/tarantool/cartridge/issues/1457
- [ ] MVP for integration topology module with Cartridge
- [ ] Finalize

**Comment by artur-barsegyan** [comment]
Depends on roadmap-internal#7.

**Comment by filonenko-mikhail** [comment]
Soooo,
I do not feel that this ticket is actual these days. 
The external config storage definitely required, but it is veeery complex task with more activity and pull requests and blood and pain in it. Gently closing.

**Comment by sharonovd** [comment]
(laughing demonically)
